import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/layout/ThemeProvider";
import Sidebar from "@/components/layout/dashboard/Sidebar";
import Navbar from "@/components/layout/dashboard/Navbar";
import StoreProvider from "@/components/layout/StoreProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <StoreProvider>
            <main className="h-screen flex">
              <Sidebar />
              <div className="flex-1">
                <Navbar />
                <div className="p-3 bg-primary/10 dark:bg-background h-[calc(100vh-60px)]">
                  {children}
                </div>
              </div>
            </main>
          </StoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
