import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/layout/ThemeProvider";
import Navbar from "@/components/layout/dashboard/Navbar";
import StoreProvider from "@/components/layout/StoreProvider";
import SidebarLayout from "@/components/layout/SidebarLayout";
import { menus } from "@/constants";
import AuthInitializer from "@/components/layout/AuthInitializer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main lang="en" suppressHydrationWarning>
      <div className={`${poppins.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <StoreProvider>
            <AuthInitializer />
            <div className="flex">
              <SidebarLayout menus={menus} />
              <div className="flex-1">
                <Navbar />
                <div className="p-3 sm:p-5 bg-primary/10 dark:bg-background">
                  {children}
                </div>
              </div>
            </div>
          </StoreProvider>
        </ThemeProvider>
      </div>
    </main>
  );
}
