import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import StoreProvider from "@/components/layout/StoreProvider";
import Header from "@/components/layout/home/header/Header";
import Footer from "@/components/layout/home/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main lang="en" suppressHydrationWarning>
      <div className={`${poppins.className} antialiased`}>
        <StoreProvider>
          {/* User */}
          <Header />
          {children}
          <Footer />
        </StoreProvider>
      </div>
    </main>
  );
}
